# Generated by Django 5.1.3 on 2024-11-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divancategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='divan_images/'),
        ),
    ]
