# Generated by Django 5.1.3 on 2024-11-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baburnoma',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='boburnoma_pdfs/'),
        ),
    ]
