# Generated by Django 5.1.3 on 2024-11-13 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_divancategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divantext',
            name='little_group',
        ),
        migrations.AddField(
            model_name='divantext',
            name='devon_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='main.divangroup'),
        ),
        migrations.DeleteModel(
            name='DivanLittleGroup',
        ),
    ]
