# Generated by Django 5.1.4 on 2025-01-08 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_boburnoma'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('image', models.ImageField(upload_to='devon/categories/', verbose_name='Rasm')),
                ('count', models.IntegerField(default=0, verbose_name='Soni')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Devon kategoriyasi',
                'verbose_name_plural': 'Devon kategoriyalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DevonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Matn')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.devoncategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Devon matni',
                'verbose_name_plural': 'Devon matnlari',
                'ordering': ['order'],
            },
        ),
    ]
