# Generated by Django 5.1.4 on 2025-01-08 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_devoncategory_devonitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='divancategory',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='main.divancategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
