# Generated by Django 5.1.4 on 2025-01-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_divancategory_count_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='main.devoncategory'),
        ),
        migrations.RemoveField(
            model_name='divangroup',
            name='category',
        ),
        migrations.RemoveField(
            model_name='divantext',
            name='devon_group',
        ),
        migrations.CreateModel(
            name='DevonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.devoncategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Devon guruhi',
                'verbose_name_plural': 'Devon guruhlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DevonText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Matn')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='main.devongroup', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Devon matni',
                'verbose_name_plural': 'Devon matnlari',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='DivanCategory',
        ),
        migrations.DeleteModel(
            name='DivanGroup',
        ),
        migrations.DeleteModel(
            name='DivanText',
        ),
    ]
