# Generated by Django 5.1.4 on 2025-01-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_work_category_remove_divangroup_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baburnoma',
            options={'verbose_name': 'Boburnoma', 'verbose_name_plural': 'Boburnoma'},
        ),
        migrations.AddField(
            model_name='baburnoma',
            name='text_content',
            field=models.TextField(blank=True, help_text='Bu matn faqat qidiruv uchun ishlatiladi', verbose_name='Qidiruv uchun matn'),
        ),
        migrations.AlterField(
            model_name='baburnoma',
            name='pdf_file',
            field=models.FileField(upload_to='boburnoma/', verbose_name='PDF fayl'),
        ),
        migrations.AlterField(
            model_name='baburnoma',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='baburnoma',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt'),
        ),
    ]
