# Generated by Django 5.1.4 on 2025-01-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_baburnoma_options_baburnoma_text_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name="So'z")),
                ('description', models.TextField(verbose_name='Izoh')),
            ],
            options={
                'verbose_name': "Lug'at",
                'verbose_name_plural': "Lug'atlar",
                'ordering': ['word'],
            },
        ),
    ]
