# Generated by Django 5.1.4 on 2025-01-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dictionary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dictionary',
            index=models.Index(fields=['word'], name='main_dictio_word_9b1b2c_idx'),
        ),
    ]
