# Generated by Django 5.1.5 on 2025-02-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_problem_delete_admincontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
